projects/midterm/library/urls.py
from django.conf.urls import url

from library import views


urlpatterns = [
	url(r'^$', views.index, name="index"),
	url(r'^media/$', views.MediaListView.as_view(), name='media'),
	url(r'^media/(?P<pk>\d+)$', views.MediaDetailView.as_view(), name='media-detail'),
	#url(r'^search', views.search, name="Search"),
]

projects/midterm/midterm/urls.py
from django.conf import settings
from django.conf.urls.static import static
from django.conf.urls import patterns, url
from django.conf.urls import include
from django.contrib import admin
from django.views.generic import RedirectView
urlpatterns = [
	url(r'^$', RedirectView.as_view(url='/library/', permanent=True)),
    url(r'^admin/', admin.site.urls),
    url(r'^library/', include('library.urls')),
] + static(settings.MEDIA_URL, document_root=settings.MEDIA_ROOT)

projects/midterm/library/models.py
from django.db import models
from django.core.urlresolvers import reverse
from django.contrib.auth.models import User
import uuid


class UserProfile(models.Model):
	user = models.OneToOneField(User)

	def __str__(self):
		return self.user.username

class Genre(models.Model):
	name = models.CharField(max_length=200, help_text="Enter a media topic")
	def __str__(self):
		return self.name

class Media(models.Model):
	mediaType = models.CharField('Type',max_length=200, help_text="The type of the media", default="Book")
	title = models.CharField(max_length=200)
	isbn = models.CharField('ISBN', max_length=13, help_text="13 character ISBN number", blank=True)
	topic = models.ForeignKey(Genre, on_delete=models.SET_NULL, null=True, related_name="Topic")
	subtopics = models.ManyToManyField(Genre, help_text="Select the subtopics for this book")
	image = models.FileField(upload_to='images/', null=True)

	def __str__(self):
		return self.title

	def get_absolute_url(self):
		return reverse('media-detail', args=[str(self.id)])

class MediaInstance(models.Model):
	id = models.UUIDField(primary_key=True, default=uuid.uuid4, help_text="Unique ID for this media")
	media = models.ForeignKey('Media', on_delete=models.SET_NULL, null=True)
	due_date = models.DateField(null=True, blank=True)
	rental_history = models.ManyToManyField(UserProfile, help_text="Select the past renters")
	borrower = models.ForeignKey(UserProfile, on_delete=models.SET_NULL, null=True, blank=True, related_name="Borrower")


	AVAILABILITY = (
		('a', 'Available'),
		('o', 'On Loan'),
	)

	status = models.CharField(max_length=1, choices=AVAILABILITY, blank=True, default='a', help_text="Media availability")

	class Meta:
		ordering = ["due_date"]

	def __str__(self):
		return '%s (%s)' % (self.id, self.media.title)

projects/midterm/library/views.py
from django.shortcuts import render
from django.core.urlresolvers import reverse
from django.views import generic
from library.models import Media, UserProfile, MediaInstance, Genre

def index(request):
	context_dict={}
	context_dict['num_media'] = Media.objects.all().count()
	context_dict['num_inst'] = MediaInstance.objects.all().count()
	context_dict['num_avail'] = MediaInstance.objects.filter(status__exact='a').count()
	return render(request, 'library/index.html', context_dict)

class MediaListView(generic.ListView):
    model = Media

class MediaDetailView(generic.DetailView):
    model = Media

projects/midterm/templates/library/base.html
<!DOCTYPE html>
{% load staticfiles %}
<html lang="en">
<head>
  
  {% block title %}<title>Library</title>{% endblock %}
  <meta charset="utf-8">
  <meta name="viewport" content="width=device-width, initial-scale=1">
  <link rel="stylesheet" href="https://maxcdn.bootstrapcdn.com/bootstrap/3.3.7/css/bootstrap.min.css">
  
  <!-- Add additional CSS in static file -->
  <link rel="stylesheet" href="{% static 'css/style.css' %}">
</head>

<body>

  <div class="container-fluid">

    <div class="row">
      <div class="col-sm-2">
      {% block sidebar %}
      <ul class="sidebar-nav">
          <li><a href="{% url 'index' %}">Home</a></li>
          <li><a href="{% url 'media' %}">All Media</a></li>
          <li><a href="">Library Search</a></li>
          <li><a href="">User Inventory</a></li>
      </ul>
     {% endblock %}
      </div>
      <div class="col-sm-10 ">
      {% block content %}{% endblock %}
      </div>
    </div>

  </div>
</body>
</html>

projects/midterm/templates/library/index.html
{% extends 'library/base.html' %}
{% load staticfiles %}

{% block content %}
<h1>Library Home</h1>

  <p>Welcome to the library</p>

<h2>Current Inventory</h2>

  <p>The library has the following record counts:</p>
  <ul>
    <li><strong>Media:</strong> {{ num_media }}</li>
    <li><strong>Copies:</strong> {{ num_inst }}</li>
    <li><strong>Copies available:</strong> {{ num_avail }}</li>
  </ul>

{% endblock %}

projects/midterm/templates/library/media_detail.html
{% extends 'library/base.html' %}
{% load staticfiles %}

{% block content %}
  <h1>Title: {{ media.title }}</h1>

  <p><strong>ISBN:</strong> {{ media.isbn }}</p>  
  <p><strong>Topic:</strong>{{ media.topic }}</p> 
  <p><strong>SubTopics:</strong> {% for subtopics in media.subtopics.all %} {{ subtopics }}{% if not forloop.last %}, {% endif %}{% endfor %}</p>  

  <div style="margin-left:20px;margin-top:20px">
    <h4>Copies</h4>

    {% for copy in media.mediainstance_set.all %}
    <hr>
    <p class="{% if copy.status == 'a' %}text-success{% elif copy.status == 'd' %}text-danger{% else %}text-warning{% endif %}">{{ copy.get_status_display }}</p>
    {% if copy.status != 'a' %}<p><strong>Due to be returned:</strong> {{copy.due_back}}</p>{% endif %}
    <p class="text-muted"><strong>Id:</strong> {{copy.id}}</p>
    {% endfor %}
  </div>
{% endblock %}

projects/midterm/templates/library/media_list.html
{% extends 'library/base.html' %}
{% load staticfiles %}

{% block content %}
    <h1>Media List</h1>

    {% if media_list %}
    <ul>

      {% for media in media_list %}
      <li>
        <a href="{{ media.get_absolute_url }}">{{ media.title }}</a> ({{media.topic}})
      </li>
      {% endfor %}

    </ul>
    {% else %}
      <p>There are no books in the library.</p>
    {% endif %}       
{% endblock %}